katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name="show_todolist"),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', show_create_task, name='show_create_task'),
    path('update/<int:pk>/', update, name='update'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('json/', show_json, name='show_json'),
    path('add/', add_task, name='add_task'),
]

todolist/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null=False, blank=False,auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

todolist/views.py
from django.shortcuts import get_object_or_404, render
from todolist.models import Task
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core import serializers
from todolist.models import Task
from todolist.forms import TaskForm
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_task = Task.objects.filter(user=request.user)
    context = {
        'data_task': data_task,
        'user': request.user,
    }
    return render(request, "todolist.html", context)


@login_required(login_url='/todolist/login/')
def show_create_task(request):
    form = TaskForm()
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('todolist:show_todolist')
        
    context = {'form':form}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
def update(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_finished:
        task.is_finished = False
    else:
        task.is_finished = True
    task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete(request, pk):
    task = Task.objects.get(id=pk)
    if task:
        task.delete()
        return redirect('todolist:show_todolist')
        
    messages.error(request, 'Error! Tidak dapat menghapus task')
    return redirect('todolist:show_todolist')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response


@login_required(login_url='/todolist/login/')
def show_json(request):
    user = request.user
    data = Task.objects.filter(user=user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


@csrf_exempt
def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        todo = Task.objects.create(title=title, description=description,date=datetime.date.today(), is_finished=False, user=request.user)
        result = {
            'pk':todo.pk,
            'fields':{
                'title':todo.title,
                'description':todo.description,
                'is_finished':todo.is_finished,
                'date':todo.date,
            }
        }
        return JsonResponse(result)    
    return HttpResponseBadRequest()

todolist/templates/create-todo.html
{% extends 'base.html' %}

{% block meta %}
<title>Add Task</title>
{% endblock meta %}

{% block content %}

<style>
    .create_task {
        margin: 125px auto 0;
        max-width: 400px;
    }
    .form-group {
        margin-bottom: 15px;
    }
    h1 {
        margin-bottom: 35px;
    }
</style>

<body>
    <div class = "create_task" style="text-align: center;">

        <h1>Tambah Task</h1>
    
        <form method="POST" action="">
            {% csrf_token %}
            
            <div class="form-group">
                <h5>Title</h5>
                <input type="text" name="title" placeholder="Title" class="form-control">
            </div>
    
            <div class="form-group">
                <h5>Description</h5>
                <input type="text" name="description" placeholder="Description" class="form-control desc">
            </div>

            <div class="form-group">
                <input class="btn btn-success col-12" type="submit" value="Tambah">
            </div>
        </form>
    
    </div>
</body>


{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<style>
    .login {
        margin: 180px auto 0;
        max-width: 400px;
    }
    .form-group {
        margin-bottom: 15px;
    }
</style>

<body>
    <div class = "login" style="text-align: center;">
        
        <h1 style="margin-bottom: 25px;">Login</h1>
    
        <form method="POST" action="">

            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="username" placeholder="Username" class="form-control">
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="Password" class="form-control">
            </div>
            <div class="form-group">
                <input class="btn btn-primary col-12" type="submit" value="Login">
            </div>
        </form>

        
    
        {% if messages %}
            <ul style="list-style-type: none;">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        
        <p3>Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></p>
        
    
    </div>
</body>


{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %} {% block meta %}
<title>Todolist</title>
<style>
    .navbar {
        margin-bottom: 50px;
    }
    .todolist {
        font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif
    }
    a {
        text-decoration: none;
        color: #ffffff;
    }
    a:hover {
        color: inherit;
    }
    h2 {
        margin-bottom: 20px;
    }
    .table {
        overflow-wrap: break-word;
        margin-top: 30px;
    }
    .card-body:hover {
        background:rgb(234, 234, 234);
        transition-duration: 0.15s;
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);

    }
</style>
{% endblock meta %} {% block content %}

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
    $(document).ready(function () {
      const card = (data) => `
        
                <div class="col">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <small class="text-muted">${data.fields.date}</small>
                            <h3 class="card-text mb-3">${data.fields.title}</h3>
                            <p class="card-text">${data.fields.description}</p>
                            ${ data.fields.is_finished ? `<h6 class="text-success">Selesai</h6>` : `<h6 class="text-danger">Belum Selesai</h6>`}
                            <div class="btn-group">
                                
                                <div onclick="location.href='/todolist/update/${data.pk}/'" class="cursor-pointer">
                                    <button><a class="btn btn-primary btn-outline-light">Ubah Status</a></button>
                                </div>
                                <div onclick="location.href='/todolist/delete/${data.pk}/'" class="cursor-pointer">
                                    <button><a class="btn btn-primary btn-outline-light">Hapus Task</a></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        `
      const addCard = (data) => {
        return $('#todo').append(card(data))
      }

      const removeCard = (task) => {
        $(`#${task.pk}`).click(function () {
          $.ajax({
            url: `/todolist/delete/${task.pk}`,
            type: 'DELETE',
            success: function (response) {
              $(`#${task.pk}-card`).remove()
            },
          })
        })
      }

      $.get('/todolist/json', function (todo) {
        todo.map((task) => {
          addCard(task)
          removeCard(task)
        })
      })

      $('#add-todo').click(function () {
        if ($('#title').val() && $('#description').val()) {
          $.post(
            '/todolist/add/',
            {
              title: $('#title').val(),
              description: $('#description').val(),
            },
            function (res, status) {
              if (status == 'success') {
                addCard(res)
                $('#title').val('')
                $('#description').val('')
                removeCard(res)
              }
            },
          )
        }
      })
    })
  </script>
</head>

{% if user.is_authenticated %}
<!-- NAVBAR -->
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0275d8;">
        <div class="container-fluid py-2 px-4">
            <a class="navbar-brand px-2" href="#" style="color: #ffffff;">Welcome, {{user}}!</a>
            <button class="btn btn-danger mx-3" style="background-color: #f3f3f3; color: #0275d8; border: #ffffff;" 
                type="submit" onclick="location.href=`{% url 'todolist:logout' %}`">Logout</button>
            </div>
    </nav>
    
    <div class="mx-8" style="text-align: center;">      
    
    <h2>To Do List</h2>
    
      <button data-bs-toggle="modal" data-bs-target="#exampleModal"class="btn btn-primary col-6" style="margin-bottom: 25px;"><a>Tambah Task</a></button>

    
      <div
        class="modal fade"
        id="exampleModal"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered relative w-auto pointer-events-none">
            <div class="modal-content" style="background-color: #0275d8;">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">
                    Tambah Task
                </h1>
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                ></button>
                </div>
                <div class="modal-body">
                <div class="flex justify-center">
                    <div class="lg:w-64 mt-3">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <label class="block">
                        
                            Title
                        <input
                            type="text"
                            name="title"
                            id="title"
                            class=""
                            placeholder="Title"
                            required
                        />
                        </label>
        
                        <label class="block mt-2">
                        <span
                            class=""
                        >
                            Description
                        </span>
                        <input
                            type="text"
                            name="description"
                            id="description"
                            class=""
                            placeholder="Description"
                            required
                        />
                        </label>
                    </form>
                    </div>
                </div>
                </div>
                <div class="modal-footer">
                <button
                    type="button"
                    class="rounded-xl btn btn-success btn-outline-light"
                    data-bs-dismiss="modal"
                >
                    Cancel
                </button>
        
                <button
                    id="add-todo"
                    type="button"
                    class="inline-flex space-x-2 items-center justify-end px-6 py-3 rounded-xl btn btn-success btn-outline-light"
                    data-bs-dismiss="modal"
                >
                    Tambah Task
                </button>
                </div>
            </div>
            </div>
        </div>
        
        <div id="todo" class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"></div>
        
        {% else %}
        <div></div>
        </div>
    
        <div class="todolist">
        <div style="text-align: center;">
    
            
        
        <div class="mb-16 grid lg:grid-cols-2 md:grid-cols-1 gap-5 mt-8 sm:mt-5" id="todo"></div>
        </div>
    </div>
</body>

{% endif %} {% endblock content %}